### ISSUE TITLE
Deprecated: mb_convert_encoding()

### ISSUE THREAD

**Issue by adamgreenough** [giuliopons/bright-link-previews#11]
Deprecated: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /home/addy/addy.codes/public/wp-content/plugins/bright-link-previews/index.php on line 226

**Comment by addyzone** [comment]
Fixed in https://github.com/giuliopons/bright-link-previews/pull/10

**Comment by giuliopons** [comment]
I've merged your code.
Thank you.
