### ISSUE TITLE
Bright Links Preview somehow changes the char encoding of elements on the page

### ISSUE THREAD

**Issue by jvandriel** [giuliopons/bright-link-previews#14]
After the latest update (v1.82) I noticed BLP somehow changes some of the html encoded symbols on a page into question marks, as the screenshots illustrate.

- BLP activated:
<img width="140" alt="BLP-activated" src="https://github.com/giuliopons/bright-link-previews/assets/7320889/5c080edc-9bfa-43a0-89df-641120a0f7a9">

- BLP deactivated:
<img width="145" alt="BLP-deactivated" src="https://github.com/giuliopons/bright-link-previews/assets/7320889/e01f094a-5d3c-4f74-9187-577a1d652738">

**Comment by giuliopons** [comment]
I think it's solved.
